import { ExerciseItem } from '../types/exercise';

export const DEFAULT_EXERCISES_DATABASE: Omit<ExerciseItem, 'created_at' | 'updated_at'>[] = [
  // ─── 1. PETTO (15 Esercizi) ────────────────────────────────────────────────
  {
    id: 'ex-petto-01',
    name: 'Distensioni Panca Piana con Bilanciere',
    category: 'Petto',
    target_specifico: 'Sternocostale (Fasci medi)',
    pattern_movimento: 'Spinta Orizzontale',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
    piano_movimento: 'Sagittale',
    catena_cinetica: 'Aperta',
    gradi_liberta: 2,
    instructions: 'Posizionarsi con 5 punti di contatto, scapole addotte e depresse. Discesa controllata al punto medio dello sterno, spinta esplosiva senza perdere il controllo scapolare.',
    muscoli_coinvolti: [
      { muscolo: 'Grande pettorale (sternocostale)', ruolo: 'Target', percentuale: 75 },
      { muscolo: 'Tricipite brachiale', ruolo: 'Sinergico', percentuale: 50 },
      { muscolo: 'Deltoide anteriore', ruolo: 'Sinergico', percentuale: 45 },
      { muscolo: 'Cuffia dei rotatori & Gran dorsale', ruolo: 'Stabilizzatore', percentuale: 30 },
    ],
    parametri_chiave: {
      rom: 'Completo fino a sfioramento sterno',
      curva_resistenza: 'Ascendente',
      punto_picco: 'Chiusura a braccia quasi distese',
      tipo_stimolo: 'Forza',
      tut: { min: 30, max: 45 },
      recupero: { min: 120, max: 180 },
    },
    sicurezza: {
      controindicazioni: ['Instabilità anteriore di spalla', 'Sindrome da impingement sub-acromiale'],
      criteri_arresto: ['Dolore anteriore spalla', 'Perdita assetto scapolare'],
      compensi_da_evitare: ['Spalle anteriorizzate in spinta', 'Rimbalzo sul petto'],
      tolleranze: 'Ridurre ROM con board o floor press in caso di fastidi articolari',
    },
  },
  {
    id: 'ex-petto-02',
    name: 'Distensioni Panca Inclinata 30° con Bilanciere',
    category: 'Petto',
    target_specifico: 'Clavicolare (Fasci alti)',
    pattern_movimento: 'Spinta Orizzontale',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
    piano_movimento: 'Sagittale',
    catena_cinetica: 'Aperta',
    instructions: 'Inclinazione panca a 30° per massimizzare il reclutamento del fascio clavicolare minimizzando il lavoro del deltoide anteriore.',
    muscoli_coinvolti: [
      { muscolo: 'Grande pettorale (clavicolare)', ruolo: 'Target', percentuale: 75 },
      { muscolo: 'Deltoide anteriore', ruolo: 'Sinergico', percentuale: 55 },
      { muscolo: 'Tricipite brachiale', ruolo: 'Sinergico', percentuale: 45 },
    ],
  },
  {
    id: 'ex-petto-03',
    name: 'Distensioni Panca Piana con Manubri',
    category: 'Petto',
    target_specifico: 'Sternocostale (Fasci medi)',
    pattern_movimento: 'Spinta Orizzontale',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
    piano_movimento: 'Sagittale',
    catena_cinetica: 'Aperta',
    instructions: 'Permette maggiore libertà articolare ai polsi e un allungamento più profondo rispetto al bilanciere.',
  },
  {
    id: 'ex-petto-04',
    name: 'Distensioni Panca Inclinata 30° con Manubri',
    category: 'Petto',
    target_specifico: 'Clavicolare (Fasci alti)',
    pattern_movimento: 'Spinta Orizzontale',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-petto-05',
    name: 'Chest Press Convergente su Macchina',
    category: 'Petto',
    target_specifico: 'Clavicolare / Sternocostale',
    pattern_movimento: 'Spinta Orizzontale',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-petto-06',
    name: 'Dip alle Parallele (Focus Petto)',
    category: 'Petto',
    target_specifico: 'Costale / Fasci Bassi',
    pattern_movimento: 'Spinta Verticale',
    equipment: 'Corpo Libero',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },
  {
    id: 'ex-petto-07',
    name: 'Croci con Manubri su Panca Piana',
    category: 'Petto',
    target_specifico: 'Sternocostale (Allungamento)',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Intermedio',
    progression_friendly: false,
  },
  {
    id: 'ex-petto-08',
    name: 'Croci con Manubri su Panca Inclinata',
    category: 'Petto',
    target_specifico: 'Clavicolare (Allungamento)',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Intermedio',
    progression_friendly: false,
  },
  {
    id: 'ex-petto-09',
    name: 'Croci ai Cavi Medi (Cable Crossover)',
    category: 'Petto',
    target_specifico: 'Sternocostale (Tensione Continua)',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-petto-10',
    name: 'Croci ai Cavi Bassi (Low-to-High)',
    category: 'Petto',
    target_specifico: 'Clavicolare (Fasci Alti)',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-petto-11',
    name: 'Croci ai Cavi Alti (High-to-Low)',
    category: 'Petto',
    target_specifico: 'Costale / Fasci Bassi',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-petto-12',
    name: 'Pec Deck / Butterfly Machine',
    category: 'Petto',
    target_specifico: 'Sternocostale (Picco Accorciamento)',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-petto-13',
    name: 'Push-up / Piegamenti a Terra',
    category: 'Petto',
    target_specifico: 'Petto Globale & Core',
    pattern_movimento: 'Spinta Orizzontale',
    equipment: 'Corpo Libero',
    bilateralita: 'Bilaterale',
    tipo: 'Resistenza',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-petto-14',
    name: 'Distensioni su Panca Declinata con Bilanciere',
    category: 'Petto',
    target_specifico: 'Costale / Fasci Bassi',
    pattern_movimento: 'Spinta Orizzontale',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-petto-15',
    name: 'Floor Press con Manubri',
    category: 'Petto',
    target_specifico: 'Sternocostale (Lockout / Spalla-Safe)',
    pattern_movimento: 'Spinta Orizzontale',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Prehab / Riabilitativo',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },

  // ─── 2. DORSO (18 Esercizi) ────────────────────────────────────────────────
  {
    id: 'ex-dorso-01',
    name: 'Trazioni alla Sbarra Presa Prona (Pull-up)',
    category: 'Dorso',
    target_specifico: 'Gran Dorsale & Trapezio',
    pattern_movimento: 'Trazione Verticale',
    equipment: 'Corpo Libero',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },
  {
    id: 'ex-dorso-02',
    name: 'Trazioni alla Sbarra Presa Supina (Chin-up)',
    category: 'Dorso',
    target_specifico: 'Gran Dorsale & Bicipite',
    pattern_movimento: 'Trazione Verticale',
    equipment: 'Corpo Libero',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-dorso-03',
    name: 'Lat Machine Presa Larga Prona',
    category: 'Dorso',
    target_specifico: 'Gran Dorsale Toracico',
    pattern_movimento: 'Trazione Verticale',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-dorso-04',
    name: 'Lat Machine Presa Neutra Stretta (V-Bar)',
    category: 'Dorso',
    target_specifico: 'Gran Dorsale Fasci Bassi',
    pattern_movimento: 'Trazione Verticale',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-dorso-05',
    name: 'Pulldown Unilaterale al Cavo Alto',
    category: 'Dorso',
    target_specifico: 'Gran Dorsale Fasci Iliaci',
    pattern_movimento: 'Trazione Verticale',
    equipment: 'Cavi',
    bilateralita: 'Unilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-dorso-06',
    name: 'Pullover con Manubrio su Panca Trasversale',
    category: 'Dorso',
    target_specifico: 'Gran Dorsale (Allungamento)',
    pattern_movimento: 'Trazione Verticale',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Intermedio',
    progression_friendly: false,
  },
  {
    id: 'ex-dorso-07',
    name: 'Pullover al Cavo Alto con Corda / Barra',
    category: 'Dorso',
    target_specifico: 'Gran Dorsale (Accorciamento)',
    pattern_movimento: 'Trazione Verticale',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-dorso-08',
    name: 'Rematore con Bilanciere Presa Prona 45°',
    category: 'Dorso',
    target_specifico: 'Spessore Dorso / Trapezio Medio',
    pattern_movimento: 'Trazione Orizzontale',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Molto Alto',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },
  {
    id: 'ex-dorso-09',
    name: 'Rematore Pendlay (Dead-Stop Row)',
    category: 'Dorso',
    target_specifico: 'Dorso Globale & Potenza',
    pattern_movimento: 'Trazione Orizzontale',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Potenza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Molto Alto',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },
  {
    id: 'ex-dorso-10',
    name: 'Rematore con Manubrio Singolo su Panca',
    category: 'Dorso',
    target_specifico: 'Gran Dorsale Unilaterale',
    pattern_movimento: 'Trazione Orizzontale',
    equipment: 'Manubri',
    bilateralita: 'Unilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-dorso-11',
    name: 'Seal Row con Manubri su Panca Inclinata',
    category: 'Dorso',
    target_specifico: 'Trapezio Medio & Romboidi (Zero Lombari)',
    pattern_movimento: 'Trazione Orizzontale',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-dorso-12',
    name: 'Pulley Basso Presa Stretta',
    category: 'Dorso',
    target_specifico: 'Gran Dorsale & Spessore',
    pattern_movimento: 'Trazione Orizzontale',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-dorso-13',
    name: 'Pulley Basso Presa Larga Prona',
    category: 'Dorso',
    target_specifico: 'Trapezio Medio & Deltoidi Posteriori',
    pattern_movimento: 'Trazione Orizzontale',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-dorso-14',
    name: 'T-Bar Row a Supporto Toracico',
    category: 'Dorso',
    target_specifico: 'Spessore Dorso & Romboidi',
    pattern_movimento: 'Trazione Orizzontale',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-dorso-15',
    name: 'Rowing Machine a Leve Convergenti',
    category: 'Dorso',
    target_specifico: 'Gran Dorsale',
    pattern_movimento: 'Trazione Orizzontale',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-dorso-16',
    name: 'Face Pull con Corda al Cavo Alto',
    category: 'Dorso',
    target_specifico: 'Trapezio / Rotatori / Rear Delt',
    pattern_movimento: 'Trazione Orizzontale',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Mobilità',
    ruolo_esercizio: 'Prehab / Riabilitativo',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-dorso-17',
    name: 'Meadows Row al Landmine',
    category: 'Dorso',
    target_specifico: 'Gran Dorsale & Gran Rotondo',
    pattern_movimento: 'Trazione Orizzontale',
    equipment: 'Bilanciere',
    bilateralita: 'Unilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },
  {
    id: 'ex-dorso-18',
    name: 'Scrollate con Manubri / Bilanciere (Shrugs)',
    category: 'Dorso',
    target_specifico: 'Trapezio Superiore',
    pattern_movimento: 'Trazione Verticale',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },

  // ─── 3. SPALLE (14 Esercizi) ───────────────────────────────────────────────
  {
    id: 'ex-spalle-01',
    name: 'Military Press con Bilanciere in Piedi',
    category: 'Spalle',
    target_specifico: 'Deltoide Anteriore & Core',
    pattern_movimento: 'Spinta Verticale',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Molto Alto',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },
  {
    id: 'ex-spalle-02',
    name: 'Lento Avanti con Manubri Seduto',
    category: 'Spalle',
    target_specifico: 'Deltoide Anteriore / Laterale',
    pattern_movimento: 'Spinta Verticale',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-spalle-03',
    name: 'Shoulder Press Machine Convergente',
    category: 'Spalle',
    target_specifico: 'Deltoide Anteriore',
    pattern_movimento: 'Spinta Verticale',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-spalle-04',
    name: 'Alzate Laterali con Manubri in Piedi',
    category: 'Spalle',
    target_specifico: 'Deltoide Laterale',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-spalle-05',
    name: 'Alzate Laterali con Manubri Seduto',
    category: 'Spalle',
    target_specifico: 'Deltoide Laterale (Strict)',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-spalle-06',
    name: 'Alzate Laterali al Cavo Basso Singolo',
    category: 'Spalle',
    target_specifico: 'Deltoide Laterale (Tensione Continua)',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Cavi',
    bilateralita: 'Unilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-spalle-07',
    name: 'Alzate Laterali ai Cavi Incrociati Dietro la Schiena',
    category: 'Spalle',
    target_specifico: 'Deltoide Laterale (Allungamento)',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-spalle-08',
    name: 'Lateral Raise Machine',
    category: 'Spalle',
    target_specifico: 'Deltoide Laterale',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-spalle-09',
    name: 'Alzate Posteriori con Manubri su Panca Inclinata',
    category: 'Spalle',
    target_specifico: 'Deltoide Posteriore',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-spalle-10',
    name: 'Reverse Pec Deck / Rear Delt Fly',
    category: 'Spalle',
    target_specifico: 'Deltoide Posteriore',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-spalle-11',
    name: 'Rear Delt Crossover ai Cavi Alti',
    category: 'Spalle',
    target_specifico: 'Deltoide Posteriore',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-spalle-12',
    name: 'Arnold Press con Manubri',
    category: 'Spalle',
    target_specifico: 'Deltoide Completo',
    pattern_movimento: 'Spinta Verticale',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-spalle-13',
    name: 'Y-Raise su Panca Inclinata',
    category: 'Spalle',
    target_specifico: 'Trapezio Inferiore & Deltoide Laterale',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Mobilità',
    ruolo_esercizio: 'Prehab / Riabilitativo',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: false,
  },
  {
    id: 'ex-spalle-14',
    name: 'Alzate Frontali con Manubri / Bilanciere',
    category: 'Spalle',
    target_specifico: 'Deltoide Anteriore',
    pattern_movimento: 'Spinta Verticale',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },

  // ─── 4. QUADRICIPITI (14 Esercizi) ─────────────────────────────────────────
  {
    id: 'ex-quad-01',
    name: 'Back Squat con Bilanciere (High Bar)',
    category: 'Quadricipiti',
    target_specifico: 'Quadricipiti & Catena Posteriore',
    pattern_movimento: 'Squat / Accosciata',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Molto Alto',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },
  {
    id: 'ex-quad-02',
    name: 'Front Squat con Bilanciere',
    category: 'Quadricipiti',
    target_specifico: 'Retto Femorale & Vasti (Busto Eretto)',
    pattern_movimento: 'Squat / Accosciata',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Molto Alto',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },
  {
    id: 'ex-quad-03',
    name: 'Hack Squat su Slitta 45°',
    category: 'Quadricipiti',
    target_specifico: 'Quadricipiti Isolati',
    pattern_movimento: 'Squat / Accosciata',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-quad-04',
    name: 'Leg Press 45° (Piedi Bassi e Stretti)',
    category: 'Quadricipiti',
    target_specifico: 'Vasto Laterale & Mediale',
    pattern_movimento: 'Squat / Accosciata',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-quad-05',
    name: 'Pendulum Squat',
    category: 'Quadricipiti',
    target_specifico: 'Quadricipite Puro',
    pattern_movimento: 'Squat / Accosciata',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-quad-06',
    name: 'Belt Squat',
    category: 'Quadricipiti',
    target_specifico: 'Quadricipite (Zero Carico Spinale)',
    pattern_movimento: 'Squat / Accosciata',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-quad-07',
    name: 'Goblet Squat con Manubrio / Kettlebell',
    category: 'Quadricipiti',
    target_specifico: 'Quadricipiti & Mobilità Anca',
    pattern_movimento: 'Squat / Accosciata',
    equipment: 'Kettlebell',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-quad-08',
    name: 'Bulgarian Split Squat (Squat Bulgaro con Manubri)',
    category: 'Quadricipiti',
    target_specifico: 'Quadricipiti & Glutei (Unilaterale)',
    pattern_movimento: 'Affondo / Split',
    equipment: 'Manubri',
    bilateralita: 'Unilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Molto Alto',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-quad-09',
    name: 'Affondi Camminati con Manubri',
    category: 'Quadricipiti',
    target_specifico: 'Quadricipiti & Glutei',
    pattern_movimento: 'Affondo / Split',
    equipment: 'Manubri',
    bilateralita: 'Alternato',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-quad-10',
    name: 'Affondi Indietro con Manubri',
    category: 'Quadricipiti',
    target_specifico: 'Quadricipiti (Knee-Friendly)',
    pattern_movimento: 'Affondo / Split',
    equipment: 'Manubri',
    bilateralita: 'Alternato',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-quad-11',
    name: 'Step-Up su Box con Manubri',
    category: 'Quadricipiti',
    target_specifico: 'Quadricipiti & Gluteo',
    pattern_movimento: 'Affondo / Split',
    equipment: 'Manubri',
    bilateralita: 'Unilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-quad-12',
    name: 'Leg Extension Machine',
    category: 'Quadricipiti',
    target_specifico: 'Retto Femorale & Vasti (Accorciamento)',
    pattern_movimento: 'Flessione / Estensione',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-quad-13',
    name: 'Sissy Squat',
    category: 'Quadricipiti',
    target_specifico: 'Retto Femorale (Allungamento Estremo)',
    pattern_movimento: 'Squat / Accosciata',
    equipment: 'Corpo Libero',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Avanzato',
    progression_friendly: false,
  },
  {
    id: 'ex-quad-14',
    name: 'Wall Sit Isometrico',
    category: 'Quadricipiti',
    target_specifico: 'Quadricipite & Tendine Rotuleo',
    pattern_movimento: 'Squat / Accosciata',
    equipment: 'Corpo Libero',
    bilateralita: 'Bilaterale',
    tipo: 'Resistenza',
    ruolo_esercizio: 'Prehab / Riabilitativo',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: false,
  },

  // ─── 5. FEMORALI (10 Esercizi) ─────────────────────────────────────────────
  {
    id: 'ex-fem-01',
    name: 'Stacco da Terra Regolare (Deadlift)',
    category: 'Femorali',
    target_specifico: 'Catena Posteriore Completa',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Molto Alto',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },
  {
    id: 'ex-fem-02',
    name: 'Stacco Rumeno con Bilanciere (RDL)',
    category: 'Femorali',
    target_specifico: 'Femorali Hip-Dominant & Glutei',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-fem-03',
    name: 'Stacco Rumeno con Manubri',
    category: 'Femorali',
    target_specifico: 'Femorali Hip-Dominant',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-fem-04',
    name: 'Single Leg Romanian Deadlift (RDL Unilaterale)',
    category: 'Femorali',
    target_specifico: 'Femorali & Stabilità Pelvica',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Manubri',
    bilateralita: 'Unilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-fem-05',
    name: 'Good Morning con Bilanciere',
    category: 'Femorali',
    target_specifico: 'Femorali & Erettori Spinali',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },
  {
    id: 'ex-fem-06',
    name: 'Lying Leg Curl (Femorali Sdraiato)',
    category: 'Femorali',
    target_specifico: 'Femorali Knee-Dominant (Accorciamento)',
    pattern_movimento: 'Flessione / Estensione',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-fem-07',
    name: 'Seated Leg Curl (Femorali Seduto)',
    category: 'Femorali',
    target_specifico: 'Femorali Knee-Dominant (Allungamento)',
    pattern_movimento: 'Flessione / Estensione',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-fem-08',
    name: 'Standing Leg Curl Unilaterale',
    category: 'Femorali',
    target_specifico: 'Femorali Knee-Dominant',
    pattern_movimento: 'Flessione / Estensione',
    equipment: 'Macchina',
    bilateralita: 'Unilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-fem-09',
    name: 'Nordic Hamstring Curl',
    category: 'Femorali',
    target_specifico: 'Femorali Eccentrico Puro & Prevenzione',
    pattern_movimento: 'Flessione / Estensione',
    equipment: 'Corpo Libero',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Tecnico',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Avanzato',
    progression_friendly: false,
  },
  {
    id: 'ex-fem-10',
    name: 'Glute Ham Raise (GHR)',
    category: 'Femorali',
    target_specifico: 'Femorali & Glutei',
    pattern_movimento: 'Flessione / Estensione',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },

  // ─── 6. GLUTEI & ADDUTTORI (10 Esercizi) ───────────────────────────────────
  {
    id: 'ex-glu-01',
    name: 'Hip Thrust con Bilanciere',
    category: 'Glutei',
    target_specifico: 'Grande Gluteo (Max Accorciamento)',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-glu-02',
    name: 'Hip Thrust Machine Dedicata',
    category: 'Glutei',
    target_specifico: 'Grande Gluteo',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-glu-03',
    name: 'Kas Glute Bridge con Bilanciere',
    category: 'Glutei',
    target_specifico: 'Grande Gluteo (Range Ridotto Isolato)',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-glu-04',
    name: 'Glute Kickback al Cavo Basso',
    category: 'Glutei',
    target_specifico: 'Grande Gluteo Unilaterale',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Cavi',
    bilateralita: 'Unilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-glu-05',
    name: 'Abductor Machine (Seduto)',
    category: 'Glutei',
    target_specifico: 'Medio e Piccolo Gluteo',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-glu-06',
    name: 'Abduzioni d\'Anca al Cavo in Piedi',
    category: 'Glutei',
    target_specifico: 'Medio Gluteo',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Cavi',
    bilateralita: 'Unilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-glu-07',
    name: 'Adductor Machine (Adduzioni Seduto)',
    category: 'Glutei',
    target_specifico: 'Adduttori (Grande e Lungo)',
    pattern_movimento: 'Abduzione / Adduzione',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-glu-08',
    name: 'Copenhagen Plank (Adductor Bridge)',
    category: 'Glutei',
    target_specifico: 'Adduttori & Stabilità Pelvica',
    pattern_movimento: 'Core Anti-Movimento',
    equipment: 'Corpo Libero',
    bilateralita: 'Unilaterale',
    tipo: 'Mobilità',
    ruolo_esercizio: 'Prehab / Riabilitativo',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Intermedio',
    progression_friendly: false,
  },
  {
    id: 'ex-glu-09',
    name: 'Stacco Sumo con Bilanciere',
    category: 'Glutei',
    target_specifico: 'Glutei & Adduttori',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Molto Alto',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },
  {
    id: 'ex-glu-10',
    name: 'Frog Pumps con Manubrio',
    category: 'Glutei',
    target_specifico: 'Grande Gluteo (Pump Finisher)',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Resistenza',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: false,
  },

  // ─── 7. POLPACCI (5 Esercizi) ──────────────────────────────────────────────
  {
    id: 'ex-polp-01',
    name: 'Calf Raise in Piedi alla Smith Machine',
    category: 'Polpacci',
    target_specifico: 'Gastrocnemio (Ginocchio Esteso)',
    pattern_movimento: 'Flessione / Estensione',
    equipment: 'Multipower',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-polp-02',
    name: 'Calf Raise su Leg Press 45°',
    category: 'Polpacci',
    target_specifico: 'Gastrocnemio (Max Allungamento)',
    pattern_movimento: 'Flessione / Estensione',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-polp-03',
    name: 'Standing Calf Machine',
    category: 'Polpacci',
    target_specifico: 'Gastrocnemio',
    pattern_movimento: 'Flessione / Estensione',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-polp-04',
    name: 'Seated Calf Raise (Seduto a 90°)',
    category: 'Polpacci',
    target_specifico: 'Soleo (Ginocchio Flesso)',
    pattern_movimento: 'Flessione / Estensione',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-polp-05',
    name: 'Tibialis Raise al Muro',
    category: 'Polpacci',
    target_specifico: 'Tibiale Anteriore & Caviglia',
    pattern_movimento: 'Flessione / Estensione',
    equipment: 'Corpo Libero',
    bilateralita: 'Bilaterale',
    tipo: 'Mobilità',
    ruolo_esercizio: 'Prehab / Riabilitativo',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: false,
  },

  // ─── 8. BICIPITI (10 Esercizi) ─────────────────────────────────────────────
  {
    id: 'ex-bic-01',
    name: 'Curl con Bilanciere Sagomato EZ in Piedi',
    category: 'Bicipiti',
    target_specifico: 'Bicipite Globale',
    pattern_movimento: 'Flessione Gomito',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-bic-02',
    name: 'Curl con Manubri Alternato con Supinazione',
    category: 'Bicipiti',
    target_specifico: 'Capo Lungo & Corto',
    pattern_movimento: 'Flessione Gomito',
    equipment: 'Manubri',
    bilateralita: 'Alternato',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-bic-03',
    name: 'Incline Dumbbell Curl (Panca 60°)',
    category: 'Bicipiti',
    target_specifico: 'Capo Lungo (Max Allungamento)',
    pattern_movimento: 'Flessione Gomito',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-bic-04',
    name: 'Spider Curl con Bilanciere EZ su Panca Inclinata',
    category: 'Bicipiti',
    target_specifico: 'Capo Corto (Picco di Tensione)',
    pattern_movimento: 'Flessione Gomito',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-bic-05',
    name: 'Preacher Curl / Panca Scott con Bilanciere EZ',
    category: 'Bicipiti',
    target_specifico: 'Capo Corto & Brachiale',
    pattern_movimento: 'Flessione Gomito',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-bic-06',
    name: 'Hammer Curl con Manubri (Presa Neutra)',
    category: 'Bicipiti',
    target_specifico: 'Brachiale & Brachioradiale',
    pattern_movimento: 'Flessione Gomito',
    equipment: 'Manubri',
    bilateralita: 'Alternato',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-bic-07',
    name: 'Cable Biceps Curl al Cavo Basso con Barra',
    category: 'Bicipiti',
    target_specifico: 'Bicipite Globale (Tensione Continua)',
    pattern_movimento: 'Flessione Gomito',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-bic-08',
    name: 'Bayesian Curl al Cavo Basso (Di Spalle)',
    category: 'Bicipiti',
    target_specifico: 'Capo Lungo (Curva Tensione Ottimale)',
    pattern_movimento: 'Flessione Gomito',
    equipment: 'Cavi',
    bilateralita: 'Unilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-bic-09',
    name: 'High Cable Curl ai Cavi Alti (Doppio Bicipite)',
    category: 'Bicipiti',
    target_specifico: 'Capo Corto & Picco Contrazione',
    pattern_movimento: 'Flessione Gomito',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-bic-10',
    name: 'Reverse Curl con Bilanciere EZ (Presa Prona)',
    category: 'Bicipiti',
    target_specifico: 'Brachioradiale & Avambracci',
    pattern_movimento: 'Flessione Gomito',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },

  // ─── 9. TRICIPITI (10 Esercizi) ────────────────────────────────────────────
  {
    id: 'ex-tri-01',
    name: 'Distensioni Panca Piana Presa Stretta',
    category: 'Tricipiti',
    target_specifico: 'Tricipiti Completi & Petto',
    pattern_movimento: 'Spinta Orizzontale',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-tri-02',
    name: 'Dips alle Parallele (Focus Tricipiti - Busto Verticale)',
    category: 'Tricipiti',
    target_specifico: 'Tricipiti Completi',
    pattern_movimento: 'Spinta Verticale',
    equipment: 'Corpo Libero',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },
  {
    id: 'ex-tri-03',
    name: 'French Press con Bilanciere EZ su Panca',
    category: 'Tricipiti',
    target_specifico: 'Capo Lungo & Mediale',
    pattern_movimento: 'Estensione Gomito',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-tri-04',
    name: 'Skull Crusher al Cavo Basso su Panca',
    category: 'Tricipiti',
    target_specifico: 'Capo Lungo (Elbow-Friendly)',
    pattern_movimento: 'Estensione Gomito',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-tri-05',
    name: 'Triceps Pushdown al Cavo Alto con Corda',
    category: 'Tricipiti',
    target_specifico: 'Capo Laterale & Mediale',
    pattern_movimento: 'Estensione Gomito',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-tri-06',
    name: 'Triceps Pushdown con Barra a V',
    category: 'Tricipiti',
    target_specifico: 'Capo Laterale',
    pattern_movimento: 'Estensione Gomito',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-tri-07',
    name: 'Overhead Cable Extension con Corda',
    category: 'Tricipiti',
    target_specifico: 'Capo Lungo (Allungamento)',
    pattern_movimento: 'Estensione Gomito',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-tri-08',
    name: 'Overhead Extension con Manubrio a Due Mani',
    category: 'Tricipiti',
    target_specifico: 'Capo Lungo',
    pattern_movimento: 'Estensione Gomito',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-tri-09',
    name: 'Cross-Body Cable Extension (Cavi Incrociati)',
    category: 'Tricipiti',
    target_specifico: 'Capo Laterale & Lungo (Zero Stress Gomito)',
    pattern_movimento: 'Estensione Gomito',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-tri-10',
    name: 'Kickback al Cavo Basso Singolo',
    category: 'Tricipiti',
    target_specifico: 'Capo Laterale (Picco Accorciamento)',
    pattern_movimento: 'Estensione Gomito',
    equipment: 'Cavi',
    bilateralita: 'Unilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },

  // ─── 10. AVAMBRACCI (4 Esercizi) ───────────────────────────────────────────
  {
    id: 'ex-avam-01',
    name: 'Wrist Curl con Bilanciere su Panca',
    category: 'Avambracci',
    target_specifico: 'Flessori del Polso',
    pattern_movimento: 'Flessione / Estensione',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-avam-02',
    name: 'Reverse Wrist Curl con Manubri',
    category: 'Avambracci',
    target_specifico: 'Estensori del Polso',
    pattern_movimento: 'Flessione / Estensione',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-avam-03',
    name: 'Farmer\'s Walk con Trap Bar / Manubri',
    category: 'Avambracci',
    target_specifico: 'Grip Strength & Core',
    pattern_movimento: 'Trasporto / Carico',
    equipment: 'Trap Bar',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-avam-04',
    name: 'Dead Hang alla Sbarra',
    category: 'Avambracci',
    target_specifico: 'Presa & Decompressione Spinale',
    pattern_movimento: 'Core Anti-Movimento',
    equipment: 'Corpo Libero',
    bilateralita: 'Bilaterale',
    tipo: 'Mobilità',
    ruolo_esercizio: 'Prehab / Riabilitativo',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: false,
  },

  // ─── 11. ADDOME & 12. CORE (14 Esercizi) ───────────────────────────────────
  {
    id: 'ex-core-01',
    name: 'Ab-Wheel Rollout in Ginocchio',
    category: 'Core',
    target_specifico: 'Anti-Estensione Spinale',
    pattern_movimento: 'Core Anti-Movimento',
    equipment: 'Corpo Libero',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-core-02',
    name: 'Plank Tradizionale a Terra con Bracing',
    category: 'Core',
    target_specifico: 'Anti-Estensione & Stabilità',
    pattern_movimento: 'Core Anti-Movimento',
    equipment: 'Corpo Libero',
    bilateralita: 'Bilaterale',
    tipo: 'Resistenza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: false,
  },
  {
    id: 'ex-core-03',
    name: 'Pallof Press al Cavo Medio',
    category: 'Core',
    target_specifico: 'Anti-Rotazione',
    pattern_movimento: 'Core Anti-Movimento',
    equipment: 'Cavi',
    bilateralita: 'Unilaterale',
    tipo: 'Mobilità',
    ruolo_esercizio: 'Prehab / Riabilitativo',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-core-04',
    name: 'Pallof Press con Rotazione Dinamica',
    category: 'Core',
    target_specifico: 'Core Dinamico & Obliqui',
    pattern_movimento: 'Core Anti-Movimento',
    equipment: 'Cavi',
    bilateralita: 'Unilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-core-05',
    name: 'Crunch ai Cavi in Ginocchio (Cable Rope Crunch)',
    category: 'Addome',
    target_specifico: 'Retto dell\'Addome (Flessione Spinale)',
    pattern_movimento: 'Flessione / Estensione',
    equipment: 'Cavi',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-core-06',
    name: 'Hanging Leg Raise alla Sbarra (Toes to Bar)',
    category: 'Addome',
    target_specifico: 'Addome Inferiore & Flessori Anca',
    pattern_movimento: 'Flessione / Estensione',
    equipment: 'Corpo Libero',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },
  {
    id: 'ex-core-07',
    name: 'Hanging Knee Raise (Ginocchia al Petto)',
    category: 'Addome',
    target_specifico: 'Addome & Stabilità Sbarra',
    pattern_movimento: 'Flessione / Estensione',
    equipment: 'Corpo Libero',
    bilateralita: 'Bilaterale',
    tipo: 'Resistenza',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-core-08',
    name: 'Deadbug a Corpo Libero / con Fitball',
    category: 'Core',
    target_specifico: 'Anti-Estensione & Coordinazione Motoria',
    pattern_movimento: 'Core Anti-Movimento',
    equipment: 'Corpo Libero',
    bilateralita: 'Alternato',
    tipo: 'Mobilità',
    ruolo_esercizio: 'Prehab / Riabilitativo',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: false,
  },
  {
    id: 'ex-core-09',
    name: 'Bird Dog Isometrico',
    category: 'Core',
    target_specifico: 'Catena Posteriore Incrociata',
    pattern_movimento: 'Core Anti-Movimento',
    equipment: 'Corpo Libero',
    bilateralita: 'Alternato',
    tipo: 'Mobilità',
    ruolo_esercizio: 'Prehab / Riabilitativo',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: false,
  },
  {
    id: 'ex-core-10',
    name: 'Side Plank (Plank Laterale)',
    category: 'Core',
    target_specifico: 'Anti-Flessione Laterale & Obliqui',
    pattern_movimento: 'Core Anti-Movimento',
    equipment: 'Corpo Libero',
    bilateralita: 'Unilaterale',
    tipo: 'Resistenza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: false,
  },
  {
    id: 'ex-core-11',
    name: 'Suitcase Carry con Manubrio Singolo',
    category: 'Core',
    target_specifico: 'Anti-Flessione Laterale & Quadrato dei Lombi',
    pattern_movimento: 'Trasporto / Carico',
    equipment: 'Manubri',
    bilateralita: 'Unilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-core-12',
    name: 'Russian Twist con Disco',
    category: 'Addome',
    target_specifico: 'Obliqui & Rotazione Tronco',
    pattern_movimento: 'Core Anti-Movimento',
    equipment: 'Manubri',
    bilateralita: 'Alternato',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-core-13',
    name: 'Landmine Rotations',
    category: 'Core',
    target_specifico: 'Core Rotazionale & Obliqui',
    pattern_movimento: 'Core Anti-Movimento',
    equipment: 'Bilanciere',
    bilateralita: 'Alternato',
    tipo: 'Potenza',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },
  {
    id: 'ex-core-14',
    name: 'Dragon Flag su Panca Piana',
    category: 'Core',
    target_specifico: 'Anti-Estensione Avanzata',
    pattern_movimento: 'Core Anti-Movimento',
    equipment: 'Corpo Libero',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Tecnico',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Avanzato',
    progression_friendly: false,
  },

  // ─── 13. LOMBARI (4 Esercizi) ──────────────────────────────────────────────
  {
    id: 'ex-lom-01',
    name: 'Hyperextension su Panca a 45°',
    category: 'Lombari',
    target_specifico: 'Erettori Spinali & Glutei',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Ipertrofia',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-lom-02',
    name: 'Reverse Hyperextension Machine',
    category: 'Lombari',
    target_specifico: 'Erettori Spinali & Decompressione Sacrale',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Macchina',
    bilateralita: 'Bilaterale',
    tipo: 'Mobilità',
    ruolo_esercizio: 'Prehab / Riabilitativo',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-lom-03',
    name: 'Jefferson Curl con Manubrio Leggero',
    category: 'Lombari',
    target_specifico: 'Flessione/Estensione Spinale Segmentale',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Manubri',
    bilateralita: 'Bilaterale',
    tipo: 'Mobilità',
    ruolo_esercizio: 'Prehab / Riabilitativo',
    costo_sistemico: 'Basso',
    livello_difficolta: 'Avanzato',
    progression_friendly: false,
  },
  {
    id: 'ex-lom-04',
    name: 'Superman a Terra con Tenuta',
    category: 'Lombari',
    target_specifico: 'Erettori Spinali & Multifido',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Corpo Libero',
    bilateralita: 'Bilaterale',
    tipo: 'Resistenza',
    ruolo_esercizio: 'Prehab / Riabilitativo',
    costo_sistemico: 'Molto Basso',
    livello_difficolta: 'Principiante',
    progression_friendly: false,
  },

  // ─── 14. FULL BODY & 15. CONDITIONING (12 Esercizi) ────────────────────────
  {
    id: 'ex-full-01',
    name: 'Trap Bar Deadlift (Presa Neutra)',
    category: 'Full Body',
    target_specifico: 'Catena Posteriore & Quadricipiti',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Trap Bar',
    bilateralita: 'Bilaterale',
    tipo: 'Forza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Molto Alto',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-full-02',
    name: 'Clean and Press con Bilanciere',
    category: 'Full Body',
    target_specifico: 'Potenza Multi-articolare',
    pattern_movimento: 'Spinta Verticale',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Potenza',
    ruolo_esercizio: 'Tecnico',
    costo_sistemico: 'Molto Alto',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },
  {
    id: 'ex-full-03',
    name: 'Push Press con Bilanciere',
    category: 'Full Body',
    target_specifico: 'Spinta Balistica Spalle/Gambe',
    pattern_movimento: 'Spinta Verticale',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Potenza',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-full-04',
    name: 'Thruster con Bilanciere / Manubri',
    category: 'Full Body',
    target_specifico: 'Squat to Overhead Press',
    pattern_movimento: 'Squat / Accosciata',
    equipment: 'Bilanciere',
    bilateralita: 'Bilaterale',
    tipo: 'Condizionamento',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Molto Alto',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-full-05',
    name: 'Kettlebell Swing (Stile Russo)',
    category: 'Full Body',
    target_specifico: 'Potenza d\'Anca & Glutei',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Kettlebell',
    bilateralita: 'Bilaterale',
    tipo: 'Potenza',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Intermedio',
    progression_friendly: true,
  },
  {
    id: 'ex-full-06',
    name: 'Kettlebell Snatch Unilaterale',
    category: 'Full Body',
    target_specifico: 'Potenza Unilaterale & Spalla',
    pattern_movimento: 'Hinge / Cerniera d\'Anca',
    equipment: 'Kettlebell',
    bilateralita: 'Unilaterale',
    tipo: 'Potenza',
    ruolo_esercizio: 'Tecnico',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Avanzato',
    progression_friendly: true,
  },
  {
    id: 'ex-cardio-01',
    name: 'Prowler / Sled Push (Spinta Slitta)',
    category: 'Conditioning',
    target_specifico: 'Quadricipiti & Potenza Lattacida',
    pattern_movimento: 'Trasporto / Carico',
    equipment: 'Slitta',
    bilateralita: 'Alternato',
    tipo: 'Condizionamento',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-cardio-02',
    name: 'Sled Drag / Pull (Tirata Slitta Indietro)',
    category: 'Conditioning',
    target_specifico: 'Quadricipiti & Prevenzione Ginocchio',
    pattern_movimento: 'Trasporto / Carico',
    equipment: 'Slitta',
    bilateralita: 'Alternato',
    tipo: 'Mobilità',
    ruolo_esercizio: 'Prehab / Riabilitativo',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-cardio-03',
    name: 'Rowing Ergometer (Vogatore Concept2)',
    category: 'Conditioning',
    target_specifico: 'Resistenza Cardiovascolare & Dorso/Gambe',
    pattern_movimento: 'Trazione Orizzontale',
    equipment: 'Cardio Machine',
    bilateralita: 'Bilaterale',
    tipo: 'Condizionamento',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Alto',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-cardio-04',
    name: 'SkiErg (Sci di Fondo)',
    category: 'Conditioning',
    target_specifico: 'Gran Dorsale, Core & VO2 Max',
    pattern_movimento: 'Trazione Verticale',
    equipment: 'Cardio Machine',
    bilateralita: 'Bilaterale',
    tipo: 'Condizionamento',
    ruolo_esercizio: 'Complementare',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-cardio-05',
    name: 'Assault Bike / Air Bike Sprints',
    category: 'Conditioning',
    target_specifico: 'Gambe, Braccia & Potenza Anaerobica',
    pattern_movimento: 'Trasporto / Carico',
    equipment: 'Cardio Machine',
    bilateralita: 'Alternato',
    tipo: 'Condizionamento',
    ruolo_esercizio: 'Fondamentale',
    costo_sistemico: 'Molto Alto',
    livello_difficolta: 'Principiante',
    progression_friendly: true,
  },
  {
    id: 'ex-cardio-06',
    name: 'Battle Ropes (Onde Alterne & Slam)',
    category: 'Conditioning',
    target_specifico: 'Spalle, Braccia & Core Lattacido',
    pattern_movimento: 'Core Anti-Movimento',
    equipment: 'Altro',
    bilateralita: 'Alternato',
    tipo: 'Condizionamento',
    ruolo_esercizio: 'Isolamento',
    costo_sistemico: 'Medio',
    livello_difficolta: 'Principiante',
    progression_friendly: false,
  },
];
